
// This file has been generated by the GUI designer. Do not modify.
namespace Auto_Warehouse
{
	public partial class Change_Window
	{
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeview_AllProduct;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.ComboBox cb_ParamForSearch;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Entry tb_ValueForSearch;
		
		private global::Gtk.Button bn_Search;
		
		private global::Gtk.Button bn_GetAllProduct;
		
		private global::Gtk.Calendar calendar;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Entry tb_Code_ForInsert;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Entry tb_Name_ForInsert;
		
		private global::Gtk.Label label21;
		
		private global::Gtk.Entry tb_DocName_ForInsert;
		
		private global::Gtk.Label label22;
		
		private global::Gtk.Entry tb_DocNumber_ForInsert;
		
		private global::Gtk.Label label23;
		
		private global::Gtk.Entry tb_DateCreateDoc_ForInsert;
		
		private global::Gtk.Label label24;
		
		private global::Gtk.Entry tb_TodeyDate_ForInsert;
		
		private global::Gtk.Label label25;
		
		private global::Gtk.Entry tb_Count_ForInsert;
		
		private global::Gtk.Label label26;
		
		private global::Gtk.Entry tb_Warehouser_ForInsert;
		
		private global::Gtk.Label label27;
		
		private global::Gtk.Button bn_AddTo_InsertList;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview_InsertList;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Button bn_MInesDataFrom_InsertList;
		
		private global::Gtk.Button bn_AddingDataFrom_InsertList;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Auto_Warehouse.Change_Window
			this.Name = "Auto_Warehouse.Change_Window";
			this.Title = global::Mono.Unix.Catalog.GetString ("Change_Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Auto_Warehouse.Change_Window.Gtk.Container+ContainerChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Список всех товаров");
			this.vbox5.Add (this.label14);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label14]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview_AllProduct = new global::Gtk.TreeView ();
			this.treeview_AllProduct.WidthRequest = 500;
			this.treeview_AllProduct.CanFocus = true;
			this.treeview_AllProduct.Name = "treeview_AllProduct";
			this.GtkScrolledWindow1.Add (this.treeview_AllProduct);
			this.vbox5.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow1]));
			w3.Position = 1;
			this.hbox10.Add (this.vbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox5]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Параметр для поиска");
			this.vbox7.Add (this.label15);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label15]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.cb_ParamForSearch = global::Gtk.ComboBox.NewText ();
			this.cb_ParamForSearch.Name = "cb_ParamForSearch";
			this.vbox7.Add (this.cb_ParamForSearch);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.cb_ParamForSearch]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Параметр");
			this.vbox7.Add (this.label16);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label16]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.tb_ValueForSearch = new global::Gtk.Entry ();
			this.tb_ValueForSearch.CanFocus = true;
			this.tb_ValueForSearch.Name = "tb_ValueForSearch";
			this.tb_ValueForSearch.IsEditable = true;
			this.tb_ValueForSearch.InvisibleChar = '•';
			this.vbox7.Add (this.tb_ValueForSearch);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.tb_ValueForSearch]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.bn_Search = new global::Gtk.Button ();
			this.bn_Search.CanFocus = true;
			this.bn_Search.Name = "bn_Search";
			this.bn_Search.UseUnderline = true;
			this.bn_Search.Label = global::Mono.Unix.Catalog.GetString ("Поиск");
			this.vbox7.Add (this.bn_Search);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.bn_Search]));
			w9.Position = 4;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.bn_GetAllProduct = new global::Gtk.Button ();
			this.bn_GetAllProduct.CanFocus = true;
			this.bn_GetAllProduct.Name = "bn_GetAllProduct";
			this.bn_GetAllProduct.UseUnderline = true;
			this.bn_GetAllProduct.Label = global::Mono.Unix.Catalog.GetString ("Все продукты");
			this.vbox7.Add (this.bn_GetAllProduct);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.bn_GetAllProduct]));
			w10.Position = 5;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.calendar = new global::Gtk.Calendar ();
			this.calendar.CanFocus = true;
			this.calendar.Name = "calendar";
			this.calendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox7.Add (this.calendar);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.calendar]));
			w11.Position = 6;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox10.Add (this.vbox7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox7]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Сведенья о товаре");
			this.vbox8.Add (this.label18);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label18]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Номер");
			this.vbox8.Add (this.label19);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label19]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.tb_Code_ForInsert = new global::Gtk.Entry ();
			this.tb_Code_ForInsert.CanFocus = true;
			this.tb_Code_ForInsert.Name = "tb_Code_ForInsert";
			this.tb_Code_ForInsert.IsEditable = true;
			this.tb_Code_ForInsert.InvisibleChar = '•';
			this.vbox8.Add (this.tb_Code_ForInsert);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.tb_Code_ForInsert]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Название");
			this.vbox8.Add (this.label20);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label20]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.tb_Name_ForInsert = new global::Gtk.Entry ();
			this.tb_Name_ForInsert.CanFocus = true;
			this.tb_Name_ForInsert.Name = "tb_Name_ForInsert";
			this.tb_Name_ForInsert.IsEditable = true;
			this.tb_Name_ForInsert.InvisibleChar = '•';
			this.vbox8.Add (this.tb_Name_ForInsert);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.tb_Name_ForInsert]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Докуммент");
			this.vbox8.Add (this.label21);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label21]));
			w18.Position = 5;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.tb_DocName_ForInsert = new global::Gtk.Entry ();
			this.tb_DocName_ForInsert.CanFocus = true;
			this.tb_DocName_ForInsert.Name = "tb_DocName_ForInsert";
			this.tb_DocName_ForInsert.IsEditable = true;
			this.tb_DocName_ForInsert.InvisibleChar = '•';
			this.vbox8.Add (this.tb_DocName_ForInsert);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.tb_DocName_ForInsert]));
			w19.Position = 6;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Номер докуммента");
			this.vbox8.Add (this.label22);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label22]));
			w20.Position = 7;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.tb_DocNumber_ForInsert = new global::Gtk.Entry ();
			this.tb_DocNumber_ForInsert.CanFocus = true;
			this.tb_DocNumber_ForInsert.Name = "tb_DocNumber_ForInsert";
			this.tb_DocNumber_ForInsert.IsEditable = true;
			this.tb_DocNumber_ForInsert.InvisibleChar = '•';
			this.vbox8.Add (this.tb_DocNumber_ForInsert);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.tb_DocNumber_ForInsert]));
			w21.Position = 8;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата создания");
			this.vbox8.Add (this.label23);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label23]));
			w22.Position = 9;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.tb_DateCreateDoc_ForInsert = new global::Gtk.Entry ();
			this.tb_DateCreateDoc_ForInsert.CanFocus = true;
			this.tb_DateCreateDoc_ForInsert.Name = "tb_DateCreateDoc_ForInsert";
			this.tb_DateCreateDoc_ForInsert.IsEditable = true;
			this.tb_DateCreateDoc_ForInsert.InvisibleChar = '•';
			this.vbox8.Add (this.tb_DateCreateDoc_ForInsert);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.tb_DateCreateDoc_ForInsert]));
			w23.Position = 10;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Текущая дата");
			this.vbox8.Add (this.label24);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label24]));
			w24.Position = 11;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.tb_TodeyDate_ForInsert = new global::Gtk.Entry ();
			this.tb_TodeyDate_ForInsert.CanFocus = true;
			this.tb_TodeyDate_ForInsert.Name = "tb_TodeyDate_ForInsert";
			this.tb_TodeyDate_ForInsert.IsEditable = true;
			this.tb_TodeyDate_ForInsert.InvisibleChar = '•';
			this.vbox8.Add (this.tb_TodeyDate_ForInsert);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.tb_TodeyDate_ForInsert]));
			w25.Position = 12;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Количество");
			this.vbox8.Add (this.label25);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label25]));
			w26.Position = 13;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.tb_Count_ForInsert = new global::Gtk.Entry ();
			this.tb_Count_ForInsert.CanFocus = true;
			this.tb_Count_ForInsert.Name = "tb_Count_ForInsert";
			this.tb_Count_ForInsert.IsEditable = true;
			this.tb_Count_ForInsert.InvisibleChar = '•';
			this.vbox8.Add (this.tb_Count_ForInsert);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.tb_Count_ForInsert]));
			w27.Position = 14;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Интентор");
			this.vbox8.Add (this.label26);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label26]));
			w28.Position = 15;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.tb_Warehouser_ForInsert = new global::Gtk.Entry ();
			this.tb_Warehouser_ForInsert.CanFocus = true;
			this.tb_Warehouser_ForInsert.Name = "tb_Warehouser_ForInsert";
			this.tb_Warehouser_ForInsert.IsEditable = true;
			this.tb_Warehouser_ForInsert.InvisibleChar = '•';
			this.vbox8.Add (this.tb_Warehouser_ForInsert);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.tb_Warehouser_ForInsert]));
			w29.Position = 16;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.vbox8.Add (this.label27);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label27]));
			w30.Position = 17;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.bn_AddTo_InsertList = new global::Gtk.Button ();
			this.bn_AddTo_InsertList.CanFocus = true;
			this.bn_AddTo_InsertList.Name = "bn_AddTo_InsertList";
			this.bn_AddTo_InsertList.UseUnderline = true;
			this.bn_AddTo_InsertList.Label = global::Mono.Unix.Catalog.GetString ("Добавить в список");
			this.vbox8.Add (this.bn_AddTo_InsertList);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.bn_AddTo_InsertList]));
			w31.Position = 18;
			w31.Expand = false;
			w31.Fill = false;
			this.hbox10.Add (this.vbox8);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox8]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Список на удаление");
			this.vbox6.Add (this.label13);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label13]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview_InsertList = new global::Gtk.TreeView ();
			this.treeview_InsertList.WidthRequest = 500;
			this.treeview_InsertList.CanFocus = true;
			this.treeview_InsertList.Name = "treeview_InsertList";
			this.GtkScrolledWindow.Add (this.treeview_InsertList);
			this.vbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow]));
			w35.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.bn_MInesDataFrom_InsertList = new global::Gtk.Button ();
			this.bn_MInesDataFrom_InsertList.CanFocus = true;
			this.bn_MInesDataFrom_InsertList.Name = "bn_MInesDataFrom_InsertList";
			this.bn_MInesDataFrom_InsertList.UseUnderline = true;
			this.bn_MInesDataFrom_InsertList.Label = global::Mono.Unix.Catalog.GetString ("Списать");
			this.hbox11.Add (this.bn_MInesDataFrom_InsertList);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.bn_MInesDataFrom_InsertList]));
			w36.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.bn_AddingDataFrom_InsertList = new global::Gtk.Button ();
			this.bn_AddingDataFrom_InsertList.CanFocus = true;
			this.bn_AddingDataFrom_InsertList.Name = "bn_AddingDataFrom_InsertList";
			this.bn_AddingDataFrom_InsertList.UseUnderline = true;
			this.bn_AddingDataFrom_InsertList.Label = global::Mono.Unix.Catalog.GetString ("Добавить");
			this.hbox11.Add (this.bn_AddingDataFrom_InsertList);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.bn_AddingDataFrom_InsertList]));
			w37.Position = 1;
			this.vbox6.Add (this.hbox11);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox11]));
			w38.Position = 2;
			w38.Expand = false;
			w38.Fill = false;
			this.hbox10.Add (this.vbox6);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox6]));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			this.Add (this.hbox10);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1378;
			this.DefaultHeight = 523;
			this.Show ();
			this.treeview_AllProduct.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeviewAllProductRowActivated);
			this.treeview_AllProduct.CursorChanged += new global::System.EventHandler (this.OnTreeviewAllProductCursorChanged);
			this.bn_Search.Clicked += new global::System.EventHandler (this.OnBnSearchClicked);
			this.bn_GetAllProduct.Clicked += new global::System.EventHandler (this.OnBnGetAllProductClicked);
			this.calendar.DaySelectedDoubleClick += new global::System.EventHandler (this.OnCalendarDaySelectedDoubleClick);
			this.bn_AddTo_InsertList.Clicked += new global::System.EventHandler (this.OnBnAddToInsertListClicked);
			this.treeview_InsertList.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeviewInsertListRowActivated);
			this.bn_MInesDataFrom_InsertList.Clicked += new global::System.EventHandler (this.OnBnMInesDataFromInsertListClicked);
			this.bn_AddingDataFrom_InsertList.Clicked += new global::System.EventHandler (this.OnBnAddingDataFromInsertListClicked);
		}
	}
}
