
// This file has been generated by the GUI designer. Do not modify.
namespace Auto_Warehouse
{
	public partial class History_Window
	{
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview_History;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Auto_Warehouse.History_Window
			this.WidthRequest = 800;
			this.Name = "Auto_Warehouse.History_Window";
			this.Title = global::Mono.Unix.Catalog.GetString ("История операций");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Auto_Warehouse.History_Window.Gtk.Container+ContainerChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview_History = new global::Gtk.TreeView ();
			this.treeview_History.CanFocus = true;
			this.treeview_History.Name = "treeview_History";
			this.GtkScrolledWindow.Add (this.treeview_History);
			this.hbox12.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.GtkScrolledWindow]));
			w2.Position = 0;
			this.Add (this.hbox12);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 307;
			this.Show ();
		}
	}
}
