
// This file has been generated by the GUI designer. Do not modify.
namespace Auto_Warehouse
{
	public partial class Delete_Item_Window
	{
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeview_AllProduct;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview_DeleteList;
		
		private global::Gtk.Button bn_ClearDeleteList;
		
		private global::Gtk.Button bn_Delete_ItemFromList;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Auto_Warehouse.Delete_Item_Window
			this.Name = "Auto_Warehouse.Delete_Item_Window";
			this.Title = global::Mono.Unix.Catalog.GetString ("Удаление товаров");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Auto_Warehouse.Delete_Item_Window.Gtk.Container+ContainerChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview_AllProduct = new global::Gtk.TreeView ();
			this.treeview_AllProduct.CanFocus = true;
			this.treeview_AllProduct.Name = "treeview_AllProduct";
			this.GtkScrolledWindow1.Add (this.treeview_AllProduct);
			this.hbox9.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.GtkScrolledWindow1]));
			w2.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Список на удаление");
			this.vbox4.Add (this.label12);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label12]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview_DeleteList = new global::Gtk.TreeView ();
			this.treeview_DeleteList.WidthRequest = 300;
			this.treeview_DeleteList.CanFocus = true;
			this.treeview_DeleteList.Name = "treeview_DeleteList";
			this.GtkScrolledWindow.Add (this.treeview_DeleteList);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
			w5.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.bn_ClearDeleteList = new global::Gtk.Button ();
			this.bn_ClearDeleteList.CanFocus = true;
			this.bn_ClearDeleteList.Name = "bn_ClearDeleteList";
			this.bn_ClearDeleteList.UseUnderline = true;
			this.bn_ClearDeleteList.Label = global::Mono.Unix.Catalog.GetString ("Очистить список");
			this.vbox4.Add (this.bn_ClearDeleteList);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.bn_ClearDeleteList]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.bn_Delete_ItemFromList = new global::Gtk.Button ();
			this.bn_Delete_ItemFromList.CanFocus = true;
			this.bn_Delete_ItemFromList.Name = "bn_Delete_ItemFromList";
			this.bn_Delete_ItemFromList.UseUnderline = true;
			this.bn_Delete_ItemFromList.Label = global::Mono.Unix.Catalog.GetString ("Удалить товар из списка");
			this.vbox4.Add (this.bn_Delete_ItemFromList);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.bn_Delete_ItemFromList]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox9.Add (this.vbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox4]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.hbox9);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 759;
			this.DefaultHeight = 345;
			this.Show ();
			this.treeview_AllProduct.CursorChanged += new global::System.EventHandler (this.OnTreeviewAllProductCursorChanged);
			this.treeview_DeleteList.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeviewDeleteListRowActivated);
			this.bn_ClearDeleteList.Clicked += new global::System.EventHandler (this.OnBnClearDeleteListClicked);
			this.bn_Delete_ItemFromList.Clicked += new global::System.EventHandler (this.OnBnDeleteItemFromListClicked);
		}
	}
}
