
// This file has been generated by the GUI designer. Do not modify.
namespace Auto_Warehouse
{
	public partial class Help_Window
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview_Help;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Auto_Warehouse.Help_Window
			this.Name = "Auto_Warehouse.Help_Window";
			this.Title = global::Mono.Unix.Catalog.GetString ("Справка");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Auto_Warehouse.Help_Window.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview_Help = new global::Gtk.TextView ();
			this.textview_Help.CanFocus = true;
			this.textview_Help.Name = "textview_Help";
			this.GtkScrolledWindow.Add (this.textview_Help);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 561;
			this.DefaultHeight = 295;
			this.Show ();
		}
	}
}
