
// This file has been generated by the GUI designer. Do not modify.
namespace Auto_Warehouse
{
	public partial class PasswordToBDWindow
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label Пароль;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Entry tb_ServerName;
		
		private global::Gtk.Entry tb_password;
		
		private global::Gtk.Button bn_enter;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Auto_Warehouse.PasswordToBDWindow
			this.Name = "Auto_Warehouse.PasswordToBDWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Введите пароль к серверу");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Auto_Warehouse.PasswordToBDWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Имя сервера");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.Пароль = new global::Gtk.Label ();
			this.Пароль.Name = "Пароль";
			this.Пароль.LabelProp = global::Mono.Unix.Catalog.GetString ("Пароль");
			this.vbox1.Add (this.Пароль);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Пароль]));
			w2.Position = 1;
			w2.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.tb_ServerName = new global::Gtk.Entry ();
			this.tb_ServerName.CanFocus = true;
			this.tb_ServerName.Name = "tb_ServerName";
			this.tb_ServerName.IsEditable = true;
			this.tb_ServerName.InvisibleChar = '•';
			this.vbox2.Add (this.tb_ServerName);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tb_ServerName]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.tb_password = new global::Gtk.Entry ();
			this.tb_password.CanFocus = true;
			this.tb_password.Name = "tb_password";
			this.tb_password.IsEditable = true;
			this.tb_password.InvisibleChar = '•';
			this.vbox2.Add (this.tb_password);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tb_password]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w6.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.bn_enter = new global::Gtk.Button ();
			this.bn_enter.CanFocus = true;
			this.bn_enter.Name = "bn_enter";
			this.bn_enter.UseUnderline = true;
			this.bn_enter.Label = global::Mono.Unix.Catalog.GetString ("OK");
			this.hbox1.Add (this.bn_enter);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.bn_enter]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 349;
			this.DefaultHeight = 69;
			this.Show ();
			this.bn_enter.Clicked += new global::System.EventHandler (this.OnBnEnterClicked);
		}
	}
}
