
// This file has been generated by the GUI designer. Do not modify.
namespace Auto_Warehouse
{
	public partial class Add_Item_Window
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Entry tb_CodeProduct;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Entry tb_NameProduct;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry tb_ParametrProduct;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Entry tb_ParametrValue;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry tb_Producer;
		
		private global::Gtk.ComboBox cb_Producer;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry tb_TypeCounting;
		
		private global::Gtk.ComboBox cb_TypeCounting;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry tb_PriceForOne;
		
		private global::Gtk.Button bn_AddItem;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Auto_Warehouse.Add_Item_Window
			this.Name = "Auto_Warehouse.Add_Item_Window";
			this.Title = global::Mono.Unix.Catalog.GetString ("Создание навого товара");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Auto_Warehouse.Add_Item_Window.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Номер товара");
			this.hbox2.Add (this.label11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(19));
			// Container child hbox2.Gtk.Box+BoxChild
			this.tb_CodeProduct = new global::Gtk.Entry ();
			this.tb_CodeProduct.CanFocus = true;
			this.tb_CodeProduct.Name = "tb_CodeProduct";
			this.tb_CodeProduct.IsEditable = true;
			this.tb_CodeProduct.InvisibleChar = '•';
			this.hbox2.Add (this.tb_CodeProduct);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.tb_CodeProduct]));
			w2.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Название товара");
			this.hbox3.Add (this.label10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label10]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(10));
			// Container child hbox3.Gtk.Box+BoxChild
			this.tb_NameProduct = new global::Gtk.Entry ();
			this.tb_NameProduct.CanFocus = true;
			this.tb_NameProduct.Name = "tb_NameProduct";
			this.tb_NameProduct.IsEditable = true;
			this.tb_NameProduct.InvisibleChar = '•';
			this.hbox3.Add (this.tb_NameProduct);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.tb_NameProduct]));
			w5.Position = 1;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Параметр");
			this.hbox4.Add (this.label9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label9]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(35));
			// Container child hbox4.Gtk.Box+BoxChild
			this.tb_ParametrProduct = new global::Gtk.Entry ();
			this.tb_ParametrProduct.CanFocus = true;
			this.tb_ParametrProduct.Name = "tb_ParametrProduct";
			this.tb_ParametrProduct.IsEditable = true;
			this.tb_ParametrProduct.InvisibleChar = '•';
			this.hbox4.Add (this.tb_ParametrProduct);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.tb_ParametrProduct]));
			w8.Position = 1;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Значение");
			this.hbox5.Add (this.label8);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label8]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(36));
			// Container child hbox5.Gtk.Box+BoxChild
			this.tb_ParametrValue = new global::Gtk.Entry ();
			this.tb_ParametrValue.CanFocus = true;
			this.tb_ParametrValue.Name = "tb_ParametrValue";
			this.tb_ParametrValue.IsEditable = true;
			this.tb_ParametrValue.InvisibleChar = '•';
			this.hbox5.Add (this.tb_ParametrValue);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.tb_ParametrValue]));
			w11.Position = 1;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Производитель");
			this.hbox8.Add (this.label7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label7]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(15));
			// Container child hbox8.Gtk.Box+BoxChild
			this.tb_Producer = new global::Gtk.Entry ();
			this.tb_Producer.CanFocus = true;
			this.tb_Producer.Name = "tb_Producer";
			this.tb_Producer.IsEditable = true;
			this.tb_Producer.InvisibleChar = '•';
			this.hbox8.Add (this.tb_Producer);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.tb_Producer]));
			w14.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.cb_Producer = global::Gtk.ComboBox.NewText ();
			this.cb_Producer.WidthRequest = 152;
			this.cb_Producer.Name = "cb_Producer";
			this.hbox8.Add (this.cb_Producer);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.cb_Producer]));
			w15.Position = 2;
			this.vbox3.Add (this.hbox8);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Единица измерения");
			this.hbox7.Add (this.label6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.tb_TypeCounting = new global::Gtk.Entry ();
			this.tb_TypeCounting.WidthRequest = 150;
			this.tb_TypeCounting.CanFocus = true;
			this.tb_TypeCounting.Name = "tb_TypeCounting";
			this.tb_TypeCounting.IsEditable = true;
			this.tb_TypeCounting.InvisibleChar = '•';
			this.hbox7.Add (this.tb_TypeCounting);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.tb_TypeCounting]));
			w18.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.cb_TypeCounting = global::Gtk.ComboBox.NewText ();
			this.cb_TypeCounting.WidthRequest = 150;
			this.cb_TypeCounting.Name = "cb_TypeCounting";
			this.hbox7.Add (this.cb_TypeCounting);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.cb_TypeCounting]));
			w19.Position = 2;
			this.vbox3.Add (this.hbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
			w20.Position = 5;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Цена за единицу");
			this.hbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label5]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(13));
			// Container child hbox6.Gtk.Box+BoxChild
			this.tb_PriceForOne = new global::Gtk.Entry ();
			this.tb_PriceForOne.CanFocus = true;
			this.tb_PriceForOne.Name = "tb_PriceForOne";
			this.tb_PriceForOne.IsEditable = true;
			this.tb_PriceForOne.InvisibleChar = '•';
			this.hbox6.Add (this.tb_PriceForOne);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.tb_PriceForOne]));
			w22.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.bn_AddItem = new global::Gtk.Button ();
			this.bn_AddItem.CanFocus = true;
			this.bn_AddItem.Name = "bn_AddItem";
			this.bn_AddItem.UseUnderline = true;
			this.bn_AddItem.Label = global::Mono.Unix.Catalog.GetString ("Добавить");
			this.hbox6.Add (this.bn_AddItem);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.bn_AddItem]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w24.Position = 6;
			w24.Expand = false;
			w24.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 465;
			this.DefaultHeight = 240;
			this.Show ();
			this.cb_Producer.Changed += new global::System.EventHandler (this.OnCbProducerChanged);
			this.cb_TypeCounting.Changed += new global::System.EventHandler (this.OnCbTypeCountingChanged);
			this.bn_AddItem.Clicked += new global::System.EventHandler (this.OnBnAddItemClicked);
		}
	}
}
