
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action Action;
	
	private global::Gtk.Action Action1;
	
	private global::Gtk.Action Action2;
	
	private global::Gtk.Action Action3;
	
	private global::Gtk.Action refreshAction;
	
	private global::Gtk.Action pasteAction;
	
	private global::Gtk.Action dialogQuestionAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView treeView_MainData;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.ComboBox cb_SearchParametr;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Entry tb_ValueForSearch_1;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Entry tb_ValueForSearch_2;
	
	private global::Gtk.Button bn_Search;
	
	private global::Gtk.Button bn_ShowAllData;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("Меню"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Меню");
		w1.Add (this.Action, null);
		this.Action1 = new global::Gtk.Action ("Action1", global::Mono.Unix.Catalog.GetString ("Добавить/Списать"), null, null);
		this.Action1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Добавить/Списать");
		w1.Add (this.Action1, null);
		this.Action2 = new global::Gtk.Action ("Action2", global::Mono.Unix.Catalog.GetString ("Создать"), null, null);
		this.Action2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Создать");
		w1.Add (this.Action2, null);
		this.Action3 = new global::Gtk.Action ("Action3", global::Mono.Unix.Catalog.GetString ("Удалить"), null, null);
		this.Action3.ShortLabel = global::Mono.Unix.Catalog.GetString ("Удалить");
		w1.Add (this.Action3, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", global::Mono.Unix.Catalog.GetString ("Обновить"), null, "gtk-refresh");
		this.refreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Обновить");
		w1.Add (this.refreshAction, null);
		this.pasteAction = new global::Gtk.Action ("pasteAction", global::Mono.Unix.Catalog.GetString ("История"), null, "gtk-paste");
		this.pasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("История");
		w1.Add (this.pasteAction, null);
		this.dialogQuestionAction = new global::Gtk.Action ("dialogQuestionAction", global::Mono.Unix.Catalog.GetString ("Справка"), null, "gtk-dialog-question");
		this.dialogQuestionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Справка");
		w1.Add (this.dialogQuestionAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Текущее состояние");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='Action' action='Action'><menuitem name='refreshAction' action='refreshAction'/><menuitem name='pasteAction' action='pasteAction'/><menuitem name='dialogQuestionAction' action='dialogQuestionAction'/></menu><menu name='Action1' action='Action1'/><menu name='Action2' action='Action2'/><menu name='Action3' action='Action3'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeView_MainData = new global::Gtk.TreeView ();
		this.treeView_MainData.HeightRequest = 200;
		this.treeView_MainData.CanFocus = true;
		this.treeView_MainData.Name = "treeView_MainData";
		this.GtkScrolledWindow.Add (this.treeView_MainData);
		this.hbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Параметр поиска");
		this.vbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.cb_SearchParametr = global::Gtk.ComboBox.NewText ();
		this.cb_SearchParametr.Name = "cb_SearchParametr";
		this.vbox2.Add (this.cb_SearchParametr);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.cb_SearchParametr]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Что искать?");
		this.vbox2.Add (this.label3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label3]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.tb_ValueForSearch_1 = new global::Gtk.Entry ();
		this.tb_ValueForSearch_1.CanFocus = true;
		this.tb_ValueForSearch_1.Name = "tb_ValueForSearch_1";
		this.tb_ValueForSearch_1.IsEditable = true;
		this.tb_ValueForSearch_1.InvisibleChar = '•';
		this.vbox2.Add (this.tb_ValueForSearch_1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tb_ValueForSearch_1]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Значение параметра");
		this.vbox2.Add (this.label4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label4]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.tb_ValueForSearch_2 = new global::Gtk.Entry ();
		this.tb_ValueForSearch_2.CanFocus = true;
		this.tb_ValueForSearch_2.Name = "tb_ValueForSearch_2";
		this.tb_ValueForSearch_2.IsEditable = true;
		this.tb_ValueForSearch_2.InvisibleChar = '•';
		this.vbox2.Add (this.tb_ValueForSearch_2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tb_ValueForSearch_2]));
		w10.Position = 5;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.bn_Search = new global::Gtk.Button ();
		this.bn_Search.CanFocus = true;
		this.bn_Search.Name = "bn_Search";
		this.bn_Search.UseUnderline = true;
		this.bn_Search.Label = global::Mono.Unix.Catalog.GetString ("Поиск");
		this.vbox2.Add (this.bn_Search);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.bn_Search]));
		w11.Position = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.bn_ShowAllData = new global::Gtk.Button ();
		this.bn_ShowAllData.CanFocus = true;
		this.bn_ShowAllData.Name = "bn_ShowAllData";
		this.bn_ShowAllData.UseUnderline = true;
		this.bn_ShowAllData.Label = global::Mono.Unix.Catalog.GetString ("Весь список");
		this.vbox2.Add (this.bn_ShowAllData);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.bn_ShowAllData]));
		w12.Position = 7;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 615;
		this.DefaultHeight = 265;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Action1.Activated += new global::System.EventHandler (this.OnAction1Activated);
		this.Action2.Activated += new global::System.EventHandler (this.OnAction2Activated);
		this.Action3.Activated += new global::System.EventHandler (this.OnAction3Activated);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionActivated);
		this.pasteAction.Activated += new global::System.EventHandler (this.OnPasteActionActivated);
		this.dialogQuestionAction.Activated += new global::System.EventHandler (this.OnDialogQuestionActionActivated);
		this.treeView_MainData.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeViewMainDataRowActivated);
		this.treeView_MainData.CursorChanged += new global::System.EventHandler (this.OnTreeViewMainDataCursorChanged);
		this.cb_SearchParametr.Changed += new global::System.EventHandler (this.OnCbSearchParametrChanged);
		this.tb_ValueForSearch_1.Changed += new global::System.EventHandler (this.OnTbValueForSearch1Changed);
		this.bn_Search.Clicked += new global::System.EventHandler (this.OnBnSearchClicked);
		this.bn_ShowAllData.Clicked += new global::System.EventHandler (this.OnBnShowAllDataClicked);
	}
}
